import customtkinter as ctk
from tkinter import filedialog, END
import threading
import os
import re
import gc
import time

import ollama
from docling.document_converter import DocumentConverter
from redmail import gmail

# ──────────────────────────── Theme ────────────────────────────
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

FONT_FAMILY = "Segoe UI"
HEADER_FONT = (FONT_FAMILY, 22, "bold")
SECTION_FONT = (FONT_FAMILY, 14, "bold")
BODY_FONT = (FONT_FAMILY, 12)
SMALL_FONT = (FONT_FAMILY, 11)

# ──────────────────────── Core Logic ───────────────────────────

def analyze_with_llama(report_text):
    """Safely calls Ollama with error handling for CUDA/Connection issues."""
    try:
        prompt = f"""
        Analyze this blood report. Provide:
        1. A bulleted list of OUT-OF-RANGE values only.
            - format should be: "Value Name: Actual Value (Normal Range) - High or Low"
        2. A medium-length health summary.
        3. A brief recommendation.
        4. A lifestyle advice.

        Rules:
        1. Address patient as Mr. or Ms. based on the name in the report.
        2. Use simple language, avoid medical jargon.
        3. Focus on actionable insights, not just numbers.
        4. If all values are normal, say "All values are within the normal range."
        5. Provide general health advice if no issues are found.
        6. Do not mention the AI or the analysis process in the output (just the header).
        7. Do not add a header saying Blood Analysis Report anymore, just start with the content directly.

        Report:
        {report_text}
        """

        response = ollama.chat(
            model='llama3:8b',
            messages=[{'role': 'user', 'content': prompt}],
            options={
                'temperature': 0.2,
                'num_predict': 2000 
            }
        )
        return response['message']['content']
    except Exception as e:
        return f"## ❌ AI Error\nThe LLM process failed. This is usually due to a CUDA/GPU memory error or Ollama not being running.\n\nDetails: {str(e)}"


def ocr_convert(image_path):
    """Run OCR on an image. Forces CPU to save VRAM for the AI model."""
    # We initialize inside the function to ensure resources are local to the thread
    converter = DocumentConverter() 
    result = converter.convert(image_path)
    markdown_content = result.document.export_to_markdown()

    warnings = []
    for element, _level in result.document.iterate_items():
        if hasattr(element, 'prov') and element.prov:
            for p in element.prov:
                conf = getattr(p, 'confidence', None)
                if conf is None and hasattr(p, 'extra') and p.extra:
                    conf = p.extra.get("confidence")
                if conf is not None and conf < 0.80:
                    text_val = getattr(element, 'text', "[Table/Group]")
                    if text_val.strip():
                        warnings.append(f"Low Confidence ({conf:.2f}): '{text_val.strip()}'")
    
    # Cleanup OCR objects immediately
    del converter
    gc.collect() 
    
    return markdown_content, warnings


def send_email(sender, app_password, to_email, subject, body):
    gmail.username = sender
    gmail.password = app_password
    gmail.send(
        subject=subject,
        receivers=[to_email],
        text=body,
    )

# ──────────────────── Formatted Insert ─────────────────────────

DISCLAIMER = (
    "\n⚕️  DISCLAIMER: This analysis is generated by an AI model and is for "
    "informational purposes only. It is NOT a substitute for professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified "
    "healthcare provider for any medical concerns.\n"
)


def insert_formatted(textbox, raw_text):
    textbox.configure(state="normal")
    textbox.delete("1.0", END)
    w = textbox._textbox

    # ── Tag definitions ─────────────────────────────────────────
    w.tag_configure("ocr_ok", font=(FONT_FAMILY, 13, "bold"),
                    foreground="#ECFDF5", background="#065F46",
                    spacing1=4, spacing3=4, lmargin1=8, lmargin2=8)
    w.tag_configure("ocr_warn_hdr", font=(FONT_FAMILY, 13, "bold"),
                    foreground="#FEF3C7", background="#78350F",
                    spacing1=4, spacing3=4, lmargin1=8, lmargin2=8)
    w.tag_configure("section", font=(FONT_FAMILY, 13, "bold"),
                    foreground="#E0F2FE", background="#1E3A5F",
                    spacing1=4, spacing3=4, lmargin1=8, lmargin2=8)
    w.tag_configure("spacer", font=(FONT_FAMILY, 6),
                    spacing1=0, spacing3=0)
    w.tag_configure("title", font=(FONT_FAMILY, 16, "bold"),
                    foreground="#F8FAFC", spacing1=10, spacing3=8,
                    lmargin1=6, justify="center")
    w.tag_configure("bullet", font=(FONT_FAMILY, 12), foreground="#E2E8F0",
                    lmargin1=20, lmargin2=34, spacing1=2)
    w.tag_configure("body", font=(FONT_FAMILY, 12), foreground="#CBD5E1",
                    spacing1=2, lmargin1=6, lmargin2=6)
    w.tag_configure("bold", font=(FONT_FAMILY, 12, "bold"),
                    foreground="#F1F5F9")
    w.tag_configure("disclaimer", font=(FONT_FAMILY, 11, "italic"),
                    foreground="#94A3B8", background="#1E293B",
                    spacing3=4, lmargin1=8, lmargin2=8,
                    rmargin=8)

    for line in raw_text.split("\n"):
        stripped = line.strip()

        # ── Special: OCR confidence banners ─────────────────────
        if "✅" in stripped and "OCR" in stripped.upper():
            text = re.sub(r'^#{1,4}\s+', '', stripped).strip("* ")
            w.insert(END, "\n", "spacer")
            w.insert(END, f"  {text}  \n", "ocr_ok")
            continue
        if "⚠" in stripped and "OCR" in stripped.upper():
            text = re.sub(r'^#{1,4}\s+', '', stripped).strip("* ")
            w.insert(END, "\n", "spacer")
            w.insert(END, f"  {text}  \n", "ocr_warn_hdr")
            continue

        # ── Title line (all-caps BLOOD REPORT ANALYSIS) ─────────
        if stripped == "BLOOD REPORT ANALYSIS":
            w.insert(END, f"\n{stripped}\n", "title")
            continue

        # ── Section headers: ## ... or **...**
        if re.match(r'^#{1,4}\s+', stripped):
            text = re.sub(r'^#{1,4}\s+', '', stripped).strip("* ")
            w.insert(END, "\n", "spacer")
            w.insert(END, f"  {text}  \n", "section")
        elif re.match(r'^\*\*[^*]+\*\*:?$', stripped):
            text = stripped.strip("*").strip(": ")
            w.insert(END, "\n", "spacer")
            w.insert(END, f"  {text}  \n", "section")

        # ── Bullet / numbered list
        elif stripped.startswith(("- ", "• ", "* ")) or re.match(r'^\d+[\.\)]\s', stripped):
            w.insert(END, f"  {stripped}\n", "bullet")

        # ── Blank line
        elif stripped == "":
            w.insert(END, "\n", "body")

        # ── Normal paragraph with inline **bold**
        else:
            for part in re.split(r'(\*\*[^*]+\*\*)', stripped):
                if part.startswith("**") and part.endswith("**"):
                    w.insert(END, part.strip("*"), "bold")
                else:
                    w.insert(END, part, "body")
            w.insert(END, "\n", "body")

    # ── Disclaimer at the bottom ────────────────────────────────
    w.insert(END, "\n", "spacer")
    w.insert(END, DISCLAIMER, "disclaimer")

    textbox.configure(state="disabled")

# ──────────────────────── GUI Class ────────────────────────────

class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Lab Report Analyzer")
        self.geometry("960x740")
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(2, weight=1)

        self._build_header()
        self._build_controls()
        self._build_result_area()
        self._analysis_text = ""

    def _build_header(self):
        hdr = ctk.CTkFrame(self, fg_color="transparent")
        hdr.grid(row=0, column=0, sticky="ew", padx=24, pady=(18, 4))
        ctk.CTkLabel(hdr, text="🩸 Lab Report Analyzer", font=HEADER_FONT).pack(anchor="w")
        ctk.CTkLabel(hdr, text="Upload a report, run OCR, and analyze with Llama 3.", font=SMALL_FONT, text_color="#94A3B8").pack(anchor="w")

    def _build_controls(self):
        frame = ctk.CTkFrame(self, corner_radius=12)
        frame.grid(row=1, column=0, sticky="ew", padx=24, pady=10)
        frame.grid_columnconfigure((0, 1, 2), weight=1)

        # File picker
        fp = ctk.CTkFrame(frame, fg_color="transparent")
        fp.grid(row=0, column=0, columnspan=3, sticky="ew", padx=16, pady=(14, 6))
        fp.grid_columnconfigure(1, weight=1)
        ctk.CTkLabel(fp, text="Report Image", font=SECTION_FONT).grid(row=0, column=0, sticky="w")
        self.file_entry = ctk.CTkEntry(fp, placeholder_text="Select an image file...", font=BODY_FONT)
        self.file_entry.grid(row=0, column=1, sticky="ew", padx=(12, 8))
        ctk.CTkButton(fp, text="Browse", width=90, command=self._browse_file).grid(row=0, column=2)

        # Email
        ef = ctk.CTkFrame(frame, fg_color="transparent")
        ef.grid(row=1, column=0, columnspan=3, sticky="ew", padx=16, pady=(6, 6))
        ef.grid_columnconfigure((1, 3, 5), weight=1)
        self.sender_entry = ctk.CTkEntry(ef, placeholder_text="you@gmail.com", font=BODY_FONT)
        self.sender_entry.grid(row=0, column=1, sticky="ew", padx=(8, 16))
        self.password_entry = ctk.CTkEntry(ef, placeholder_text="App Password", font=BODY_FONT, show="•")
        self.password_entry.grid(row=0, column=3, sticky="ew", padx=(8, 16))
        self.target_entry = ctk.CTkEntry(ef, placeholder_text="Recipient (Optional)", font=BODY_FONT)
        self.target_entry.grid(row=0, column=5, sticky="ew", padx=(8, 0))

        # Buttons
        bf = ctk.CTkFrame(frame, fg_color="transparent")
        bf.grid(row=2, column=0, columnspan=3, sticky="ew", padx=16, pady=(6, 14))
        self.analyze_btn = ctk.CTkButton(bf, text="▶  Analyze Report", font=(FONT_FAMILY, 13, "bold"), height=38, command=self._on_analyze)
        self.analyze_btn.pack(side="left")
        self.email_btn = ctk.CTkButton(bf, text="📧  Send Email", font=(FONT_FAMILY, 13), height=38, fg_color="#475569", command=self._on_send_email, state="disabled")
        self.email_btn.pack(side="left", padx=(12, 0))
        self.status_label = ctk.CTkLabel(bf, text="", font=SMALL_FONT, text_color="#94A3B8")
        self.status_label.pack(side="left", padx=(16, 0))
        self.progress = ctk.CTkProgressBar(bf, mode="indeterminate", width=140)
        self.progress.pack(side="right")
        self.progress.set(0)

    def _build_result_area(self):
        self.result_box = ctk.CTkTextbox(self, font=BODY_FONT, corner_radius=10, wrap="word", state="disabled")
        self.result_box.grid(row=2, column=0, sticky="nsew", padx=24, pady=(0, 18))

    def _set_status(self, msg):
        self.status_label.configure(text=msg)

    def _set_busy(self, busy):
        if busy:
            self.analyze_btn.configure(state="disabled")
            self.email_btn.configure(state="disabled")
            self.progress.start()
        else:
            self.analyze_btn.configure(state="normal")
            self.progress.stop()
            self.progress.set(0)

    def _browse_file(self):
        path = filedialog.askopenfilename(filetypes=[("Images", "*.png *.jpg *.jpeg *.webp *.pdf")])
        if path:
            self.file_entry.delete(0, END)
            self.file_entry.insert(0, path)

    def _on_analyze(self):
        image_path = self.file_entry.get().strip()
        if not image_path or not os.path.isfile(image_path):
            self._set_status("⚠ Invalid file.")
            return
        self._set_busy(True)
        threading.Thread(target=self._run_analysis, args=(image_path,), daemon=True).start()

    def _run_analysis(self, image_path):
        try:
            self.after(0, lambda: self._set_status("🔍 Running OCR..."))
            markdown_content, ocr_warnings = ocr_convert(image_path)

            # Important: Clear memory before AI starts to avoid CUDA crash
            self.after(0, lambda: self._set_status("🧹 Clearing VRAM..."))
            gc.collect()
            time.sleep(1) 

            self.after(0, lambda: self._set_status("🤖 Running AI Analysis..."))
            analysis = analyze_with_llama(markdown_content)
            self._analysis_text = analysis

            def _show():
                if ocr_warnings:
                    hdr = "## ⚠ OCR Confidence Warnings\n"
                    for w in ocr_warnings:
                        hdr += f"- {w}\n"
                    hdr += "\n"
                else:
                    hdr = "## ✅ OCR High Confidence\n\n"
                full = hdr + "BLOOD REPORT ANALYSIS\n\n" + analysis
                insert_formatted(self.result_box, full)
                self._set_status("✅ Complete.")
                self._set_busy(False)
                if "❌ AI Error" not in analysis:
                    self.email_btn.configure(state="normal")

            self.after(0, _show)
        except Exception as e:
            self.after(0, lambda: self._set_status(f"❌ Error: {e}"))
            self.after(0, lambda: self._set_busy(False))

    def _on_send_email(self):
        sender, password = self.sender_entry.get().strip(), self.password_entry.get().strip()
        target = self.target_entry.get().strip() or sender
        if not sender or not password:
            self._set_status("⚠ Email credentials required.")
            return
        self._set_busy(True)
        self._set_status(f"📧 Sending to {target}...")
        threading.Thread(target=self._run_send, args=(sender, password, target), daemon=True).start()

    def _run_send(self, sender, password, target):
        try:
            send_email(sender, password, target, "BLOOD REPORT ANALYSIS", self._analysis_text)
            self.after(0, lambda: self._set_status(f"✅ Sent to {target}"))
        except Exception as e:
            self.after(0, lambda: self._set_status(f"❌ Email failed: {e}"))
        finally:
            self.after(0, lambda: self._set_busy(False))
            self.after(0, lambda: self.email_btn.configure(state="normal"))

if __name__ == "__main__":
    app = App()
    app.mainloop()